PDSapp/urls.py
from django.urls import path
from PDSapp import views

app_name = 'PDSapp'

urlpatterns = [
	path('', views.home , name='home'),
	path('excel_de_usuarios', views.excel_usuarios , name='excel_usuarios'),

	path('lista_dominio', views.lista_dominio , name='lista_dominio'),
	path('crear_dominio', views.crear_dominio , name='crear_dominio'),
	path('editar_dominio/<int:dominio_id>', views.editar_dominio , name='editar_dominio'),
	path('eliminar_dominio/<int:dominio_id>', views.eliminar_dominio, name = 'eliminar_dominio'),

	path('lista_control', views.lista_control , name='lista_control'),
	path('crear_control', views.crear_control , name='crear_control'),
	path('editar_control/<int:control_id>', views.editar_control , name='editar_control'),
	path('eliminar_control/<int:control_id>', views.eliminar_control, name = 'eliminar_control'),

	path('lista_respuesta', views.lista_respuesta , name='lista_respuesta'),
	path('crear_respuesta', views.crear_respuesta , name='crear_respuesta'),
	path('editar_respuesta/<int:respuesta_id>', views.editar_respuesta , name='editar_respuesta'),
	path('eliminar_respuesta/<int:respuesta_id>', views.eliminar_respuesta, name = 'eliminar_respuesta'),

	path('lista_responder', views.lista_responder , name='lista_responder'),
	path('crear_responder', views.crear_responder , name='crear_responder'),
	path('editar_responder/<int:opcion_id>', views.editar_responder , name='editar_responder'),
	path('eliminar_responder/<int:opcion_id>', views.eliminar_responder, name = 'eliminar_responder'),

	path('lista_aspecto_legal', views.lista_aspecto_legal , name='lista_aspecto_legal'),
	path('crear_aspecto_legal', views.crear_aspecto_legal , name='crear_aspecto_legal'),
	path('editar_aspecto_legal/<int:aspectolegal_id>', views.editar_aspecto_legal , name='editar_aspecto_legal'),
	path('eliminar_aspecto_legal/<int:aspectolegal_id>', views.eliminar_aspecto_legal, name = 'eliminar_aspecto_legal'),

	path('lista_recomendacion', views.lista_recomendacion , name='lista_recomendacion'),
	path('crear_recomendacion', views.crear_recomendacion , name='crear_recomendacion'),
	path('editar_recomendacion/<int:recomendacion_id>', views.editar_recomendacion , name='editar_recomendacion'),
	path('eliminar_recomendacion/<int:recomendacion_id>', views.eliminar_recomendacion, name = 'eliminar_recomendacion'),

	path('lista_sucursal', views.lista_sucursal , name='lista_sucursal'),
	path('crear_sucursal', views.crear_sucursal , name='crear_sucursal'),
	path('editar_sucursal/<int:sucursal_id>', views.editar_sucursal , name='editar_sucursal'),
	path('eliminar_sucursal/<int:sucursal_id>', views.eliminar_sucursal, name = 'eliminar_sucursal'),

	path('informe_diagnostico', views.informe_diagnostico , name='informe_diagnostico'),
	path('informe_diagnostico_pdf', views.informe_diagnostico_pdf , name='informe_diagnostico_pdf'),
	path('informe_pds', views.informe_pds , name='informe_pds'),
	path('informe_pds_pdf', views.informe_pds_pdf , name='informe_pds_pdf'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('PDSapp/', include('PDSapp.urls')),
    path('auth/', include('auth_PDSapp.urls')),
]

PDSapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Q

class Sucursal(models.Model):
    nombre = models.CharField(max_length=50)
    descripcion = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.nombre


rol = (
    ('OPERATIVO', 'Operativo'),
    ('DIRECTIVO', 'Directivo'),
    ('AMBOS', 'Ambos'),
)

class Perfil(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    apellido_materno = models.CharField(max_length=50)
    sucursal = models.ForeignKey(Sucursal, on_delete=models.CASCADE)
    cargo = models.CharField(choices=rol, max_length=9)

    def __str__(self):
        return str(self.user)

class Dominio(models.Model):
    perfil = models.ManyToManyField(Perfil)
    nombre = models.CharField(max_length=50)

    class Meta:
        ordering = ['nombre']

    def __str__(self):
        return self.nombre

class Control(models.Model):
    dominio = models.ForeignKey(Dominio, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=50)

    def get_promedio(self):
        numr = Respuesta.objects.filter(control=self.control).count()
        sumar = Respuesta.objects.get(get_percentage)
        perc = sumar / numr
        return perc

    class Meta:
        ordering = ['dominio']

    def __str__(self):
        return self.nombre


class Respuesta(models.Model):
    perfil = models.ForeignKey(Perfil, on_delete=models.CASCADE)
    control = models.ForeignKey(Control, on_delete=models.CASCADE)

    def get_percentage(self):
        total_count = Opcion.objects.filter((Q(respuesta__control=self.control) & (Q(dato='SI'))) | (Q(respuesta__control=self.control) & (Q(dato='NO'))) | (Q(respuesta__control=self.control) & (Q(dato='DESCONOZCO')))).count()
        cnt = Opcion.objects.filter(Q(respuesta__control=self.control) & (Q(dato='SI'))).count()
        perc = cnt * 100 / total_count
        return perc

    class Meta:
        ordering = ['control']

    def __str__(self):
        return str(self.control)


opc = (
    ('SI', 'Si'),
    ('NO', 'No'),
    ('DESCONOZCO', 'Desconozco'),
)
class Opcion(models.Model):
    respuesta = models.OneToOneField(Respuesta, on_delete=models.CASCADE)
    dato = models.CharField(choices=opc, max_length=10)

    def __str__(self):
        return self.dato

class AspectoLegal(models.Model):
    dominio = models.ManyToManyField(Dominio)
    nombre = models.CharField(max_length=50)
    descripcion = models.TextField()

    def __str__(self):
        return self.nombre

class Recomendacion(models.Model):
    control = models.ForeignKey(Control, on_delete=models.CASCADE)
    descripcion = models.TextField()
    fuente = models.CharField(max_length=50)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_actualizacion = models.DateTimeField()
    fecha_aplicacion = models.DateTimeField()
    aprobado = models.CharField(max_length=50)
    estado = models.CharField(max_length=50)


    def __str__(self):
        return self.dominio

PDSapp/forms.py
from django import forms
from .models import Perfil, Dominio, Control, Respuesta, AspectoLegal, Recomendacion, Opcion, Sucursal
from django.contrib.auth.models import User


class PerfilForm(forms.ModelForm):
    class Meta:
        model = Perfil
        fields = '__all__'

class DominioForm(forms.ModelForm):
    class Meta:
        model = Dominio
        fields = '__all__'

class ControlForm(forms.ModelForm):
    class Meta:
        model = Control
        fields = '__all__'

class RespuestaForm(forms.ModelForm):
    class Meta:
        model = Respuesta
        fields = '__all__'

class ResponderForm(forms.ModelForm):
    class Meta:
        model = Opcion
        fields = ['dato']

class AspectoLegalForm(forms.ModelForm):
    class Meta:
        model = AspectoLegal
        fields = '__all__'

class RecomendacionForm(forms.ModelForm):
    class Meta:
        model = Recomendacion
        fields = '__all__'

class SucursalForm(forms.ModelForm):
    class Meta:
        model = Sucursal
        fields = '__all__'

PDSapp/views.py
from django.shortcuts import render, redirect
from PDSapp.models import Sucursal, Perfil, Dominio, Control, AspectoLegal, Recomendacion, Respuesta, Opcion
from django.contrib.auth.models import User
from PDSapp.forms import DominioForm, ControlForm, RespuestaForm, ResponderForm, AspectoLegalForm, RecomendacionForm, SucursalForm
from django.contrib.auth.decorators import login_required, permission_required
from tablib import Dataset
from .resources import PerfilResource
from django.db.models import Q
from django.http import HttpResponse
from PDSapp.utils import render_to_pdf
from django.template.loader import get_template


@login_required
def home(request):
    template_name = 'PDSapp/home.html'
    data = {}

    data['query'] = ''

    return render(request, template_name, data)

#arreglar
def excel_usuarios(request):
    if request.method == 'POST':
        perfil_resource = PerfilResource()
        dataset = Dataset()
        new_persons = request.FILES['myfile']

        imported_data = dataset.load(new_persons.read())
        result = perfil_resource.import_data(dataset, dry_run=True)  # Test the data import

        if not result.has_errors():
            perfil_resource.import_data(dataset, dry_run=False)  # Actually import now

    return render(request, 'PDSapp/excel_usuarios.html')


@login_required
def lista_dominio(request):
	data = {}
	template_name = 'PDSapp/lista_dominio.html'
	data['dominios'] = Dominio.objects.all()

	return render(request, template_name, data)

@permission_required('PDSapp.add_dominio')
def crear_dominio(request):
	data = {}
	template_name = 'PDSapp/crear_dominio.html'

	if request.method == 'POST':
		data['form'] = DominioForm(request.POST,files=request.FILES)
		if data['form'].is_valid():
			data['form'].save()
			return redirect('PDSapp:lista_dominio')
	else:
		data['form'] = DominioForm()

	return render(request, template_name, data)

@permission_required('PDSapp.change_dominio')
def editar_dominio(request, dominio_id):
	data = {}
	template_name = 'PDSapp/editar_dominio.html'
	dominio = Dominio.objects.get(pk=dominio_id)

	if request.method == 'POST':
		data['form'] = DominioForm(request.POST,request.FILES or None, instance=dominio)
		if data['form'].is_valid():
			data['form'].save()
			return redirect('PDSapp:lista_dominio')
	else:
		data['form'] = DominioForm(instance=dominio)

	return render(request, template_name, data)

@permission_required('PDSapp.delete_dominio')
def eliminar_dominio(request, dominio_id):
	data = {}
	template_name = 'PDSapp/eliminar_dominio.html'
	data['dominio'] = Dominio.objects.get(pk=dominio_id)

	if request.method == 'POST':
		data['dominio'].delete()
		return redirect('PDSapp:lista_dominio')

	return render(request, template_name, data)


@login_required
def lista_control(request):
	data = {}
	template_name = 'PDSapp/lista_control.html'
	data['controles'] = Control.objects.all()

	return render(request, template_name, data)

@permission_required('PDSapp.add_control')
def crear_control(request):
	data = {}
	template_name = 'PDSapp/crear_control.html'

	if request.method == 'POST':
		data['form'] = ControlForm(request.POST,files=request.FILES)
		if data['form'].is_valid():
			data['form'].save()
			return redirect('PDSapp:lista_control')
	else:
		data['form'] = ControlForm()

	return render(request, template_name, data)

@permission_required('PDSapp.change_control')
def editar_control(request, control_id):
	data = {}
	template_name = 'PDSapp/editar_control.html'
	control = Control.objects.get(pk=control_id)

	if request.method == 'POST':
		data['form'] = ControlForm(request.POST,request.FILES or None, instance=control)
		if data['form'].is_valid():
			data['form'].save()
			return redirect('PDSapp:lista_control')
	else:
		data['form'] = ControlForm(instance=control)

	return render(request, template_name, data)

@permission_required('PDSapp.delete_control')
def eliminar_control(request, control_id):
	data = {}
	template_name = 'PDSapp/eliminar_control.html'
	data['control'] = Control.objects.get(pk=control_id)

	if request.method == 'POST':
		data['control'].delete()
		return redirect('PDSapp:lista_control')

	return render(request, template_name, data)


@permission_required('PDSapp.view_respuesta')
def lista_respuesta(request):
	data = {}
	template_name = 'PDSapp/lista_respuesta.html'
	data['respuestas'] = Respuesta.objects.all()

	return render(request, template_name, data)

@permission_required('PDSapp.add_respuesta')
def crear_respuesta(request):
	data = {}
	template_name = 'PDSapp/crear_respuesta.html'

	if request.method == 'POST':
		data['form'] = RespuestaForm(request.POST,files=request.FILES)
		if data['form'].is_valid():
			data['form'].save()
			return redirect('PDSapp:lista_respuesta')
	else:
		data['form'] = RespuestaForm()

	return render(request, template_name, data)

@permission_required('PDSapp.change_respuesta')
def editar_respuesta(request, respuesta_id):
	data = {}
	template_name = 'PDSapp/editar_respuesta.html'
	respuesta = Respuesta.objects.get(pk=respuesta_id)

	if request.method == 'POST':
		data['form'] = RespuestaForm(request.POST,request.FILES or None, instance=respuesta)
		if data['form'].is_valid():
			data['form'].save()
			return redirect('PDSapp:lista_respuesta')
	else:
		data['form'] = RespuestaForm(instance=respuesta)

	return render(request, template_name, data)

@permission_required('PDSapp.delete_respuesta')
def eliminar_respuesta(request, respuesta_id):
	data = {}
	template_name = 'PDSapp/eliminar_respuesta.html'
	data['respuestas'] = Respuesta.objects.get(pk=respuesta_id)

	if request.method == 'POST':
		data['respuestas'].delete()
		return redirect('PDSapp:lista_respuesta')

	return render(request, template_name, data)


@login_required
def lista_responder(request):
	data = {}
	template_name = 'PDSapp/lista_responder.html'
	data['opciones'] = Opcion.objects.filter(respuesta__perfil__user=request.user)

	return render(request, template_name, data)

@login_required
def crear_responder(request):
	data = {}
	template_name = 'PDSapp/crear_responder.html'

	if request.method == 'POST':
		data['form'] = ResponderForm(request.POST,files=request.FILES)
		if data['form'].is_valid():
			data['form'].save()
			return redirect('PDSapp:lista_responder')
	else:
		data['form'] = ResponderForm()

	return render(request, template_name, data)

@login_required
def editar_responder(request, opcion_id):
	data = {}
	template_name = 'PDSapp/editar_responder.html'
	opcion = Opcion.objects.get(pk=opcion_id)

	if request.method == 'POST':
		data['form'] = ResponderForm(request.POST,request.FILES or None, instance=opcion)
		if data['form'].is_valid():
			data['form'].save()
			return redirect('PDSapp:lista_responder')
	else:
		data['form'] = ResponderForm(instance=opcion)

	return render(request, template_name, data)

@login_required
def eliminar_responder(request, opcion_id):
	data = {}
	template_name = 'PDSapp/eliminar_responder.html'
	data['opciones'] = Opcion.objects.get(pk=opcion_id)

	if request.method == 'POST':
		data['opciones'].delete()
		return redirect('PDSapp:lista_responder')

	return render(request, template_name, data)


@login_required
def lista_aspecto_legal(request):
	data = {}
	template_name = 'PDSapp/lista_aspecto_legal.html'
	data['aspectoslegales'] = AspectoLegal.objects.all()

	return render(request, template_name, data)

@permission_required('PDSapp.add_aspectolegal')
def crear_aspecto_legal(request):
	data = {}
	template_name = 'PDSapp/crear_aspecto_legal.html'

	if request.method == 'POST':
		data['form'] = AspectoLegalForm(request.POST,files=request.FILES)
		if data['form'].is_valid():
			data['form'].save()
			return redirect('PDSapp:lista_aspecto_legal')
	else:
		data['form'] = AspectoLegalForm()

	return render(request, template_name, data)

@permission_required('PDSapp.change_aspectolegal')
def editar_aspecto_legal(request, aspectolegal_id):
	data = {}
	template_name = 'PDSapp/editar_aspecto_legal.html'
	aspectoslegales = AspectoLegal.objects.get(pk=aspectolegal_id)

	if request.method == 'POST':
		data['form'] = AspectoLegalForm(request.POST,request.FILES or None, instance=aspectoslegales)
		if data['form'].is_valid():
			data['form'].save()
			return redirect('PDSapp:lista_aspecto_legal')
	else:
		data['form'] = AspectoLegalForm(instance=aspectoslegales)

	return render(request, template_name, data)

@permission_required('PDSapp.delete_aspectolegal')
def eliminar_aspecto_legal(request, aspectolegal_id):
	data = {}
	template_name = 'PDSapp/eliminar_aspecto_legal.html'
	data['aspectoslegales'] = AspectoLegal.objects.get(pk=aspectolegal_id)

	if request.method == 'POST':
		data['aspectoslegales'].delete()
		return redirect('PDSapp:lista_aspecto_legal')

	return render(request, template_name, data)


@login_required
def lista_recomendacion(request):
	data = {}
	template_name = 'PDSapp/lista_recomendacion.html'
	data['recomendaciones'] = Recomendacion.objects.all()

	return render(request, template_name, data)

@permission_required('PDSapp.add_recomendacion')
def crear_recomendacion(request):
	data = {}
	template_name = 'PDSapp/crear_recomendacion.html'

	if request.method == 'POST':
		data['form'] = RecomendacionForm(request.POST,files=request.FILES)
		if data['form'].is_valid():
			data['form'].save()
			return redirect('PDSapp:lista_recomendacion')
	else:
		data['form'] = RecomendacionForm()

	return render(request, template_name, data)

@permission_required('PDSapp.change_recomendacion')
def editar_recomendacion(request, recomendacion_id):
	data = {}
	template_name = 'PDSapp/editar_recomendacion.html'
	recomendaciones = Recomendacion.objects.get(pk=recomendacion_id)

	if request.method == 'POST':
		data['form'] = RecomendacionForm(request.POST,request.FILES or None, instance=recomendaciones)
		if data['form'].is_valid():
			data['form'].save()
			return redirect('PDSapp:lista_recomendacion')
	else:
		data['form'] = RecomendacionForm(instance=recomendaciones)

PDSapp/templates/PDSapp/informe_pds.html
{% extends "PDSapp/base.html" %}
{% load bootstrap4 %}

{% block title %}Informe Plan Director de Seguridad{% endblock %}

{% block active_navbar_informe %}
<a class="nav-link active dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	Informes
</a>
{% endblock %}

{% block content_head %}
<div class="row mt-2">
	<div class="col-sm-6 col-md-8 col-lg-7"><h2>Informe Plan Director de Seguridad</h2></div>
	<div class="col-sm-6 col-md-8 col-lg-2"><a href="{% url 'PDSapp:informe_pds_pdf' %}" class="btn btn-success btn-block">Descargar Informe</a></div>
	<div class="col-sm-6 col-md-8 col-lg-3 mb-3"><a href="{% url 'PDSapp:lista_aspecto_legal' %}" class="btn btn-success btn-block">Aspectos legales asociados a los dominios</a></div>
</div>
{% endblock %}


{% block content_body %}
	<div class="row">
		<div class="col-md">
			<table class="table table-striped table-hover">
				<thead>
					<tr>
						<th>Dominio</th>
						<th>Control</th>
						<th>Porcentaje de cumplimiento del control</th>
						<th>Recomendación</th>
						<th>Fuente</th>
						<th>Fecha de creación</th>
						<th>Fecha de actualización</th>
						<th>Fecha de aplicación</th>
						<th>Responsable/s</th>
						<th>Cargo responsable/s</th>
						<th>Aprobado por</th>
						<th>Estado</th>
					</tr>
				</thead>

				<tbody>
				{% for control in controles %}
					<tr>
						<td style="width:110px;">{{control.dominio.nombre}}</td>
						<td style="width:110px;">{{control.nombre}}</td>
						{% for respuesta in control.respuesta_set.all %}
						<td style="width:110px;">{{respuesta.get_percentage}}%</td>
						{% endfor %}
						{% for recomendacion in control.recomendacion_set.all %}
						<td style="width:100px;">{{recomendacion.descripcion}}</td>
 						<td style="width:80px;">{{recomendacion.fuente}}</td>
 						<td style="width:80px;">{{recomendacion.fecha_creacion}}</td>
 						<td style="width:80px;">{{recomendacion.fecha_actualizacion}}</td>
 						<td style="width:80px;">{{recomendacion.fecha_aplicacion}}</td>
 						<td style="width:80px;">
 							{% with recomendacion.control.dominio.perfil.all as perfiles %}
				              {% if perfiles %}
				                {% for perfil in perfiles %}
				                <span class="badge badge-light">{{perfil.user.username}}</span>
				                {% endfor %}
				              {% endif %}
				            {% endwith %}
				        </td>
 						<td style="width:80px;">
 							{% with recomendacion.control.dominio.perfil.all as perfiles %}
				              {% if perfiles %}
				                {% for perfil in perfiles %}
				                <span class="badge badge-light">{{perfil.cargo}}</span>
				                {% endfor %}
				              {% endif %}
				            {% endwith %}
				        </td>
 						<td style="width:80px;">{{recomendacion.aprobado}}</td>
 						<td style="width:80px;">{{recomendacion.estado}}</td>
						{% endfor %}
					</tr>
				{% endfor %}
				</tbody>
			</table>
		</div>
	</div>

{% endblock %}

PDSapp/templates/PDSapp/lista_aspecto_legal.html
{% extends "PDSapp/base.html" %}
{% load bootstrap4 %}

{% block title %}Aspectos legales{% endblock %}

{% block active_navbar_lista_aspecto_legal %}<a class="nav-link active" href="{% url 'PDSapp:lista_aspecto_legal' %}">Aspectos legales</a>{% endblock %}


{% block content_head %}
<div class="row mt-2">
	<div class="col-sm-6 col-md-6 col-lg-9"><h2>Aspectos legales</h2></div>
	<div class="col-sm-6 col-md-6 col-lg-3">
		{% if perms.PDSapp.add_aspectolegal %}
		<a href="{% url 'PDSapp:crear_aspecto_legal' %}" class="btn btn-success btn-block">Crear Aspecto legal</a>
		{% endif %}
	</div>
</div>
{% endblock %}


{% block content_body %}
	<div class="row">
		<div class="col-md">
			<table class="table table-striped table-hover">
				<thead>
					<tr>
						<th>Dominio/s</th>
						<th>Aspecto legal</th>
						<th>Descripción</th>
						{% if perms.PDSapp.change_aspectolegal or perms.PDSapp.delete_aspectolegal %}
						<th>Accion</th>
						{% endif %}
					</tr>
				</thead>

				<tbody>
				{% for aspectolegal in aspectoslegales %}
					<tr>
 						<td style="width:110px;">
 							{% with aspectolegal.dominio.all as dominios %}
				              {% if dominios %}
				                {% for dominio in dominios %}
				                <span class="badge badge-light">{{dominio.nombre}}</span>
				                {% endfor %}
				              {% endif %}
				            {% endwith %}
 						</td>
 						<td style="width:50px;">{{aspectolegal.nombre}}</td>
 						<td style="width:170px;">{{aspectolegal.descripcion}}</td>
 						{% if perms.PDSapp.change_dominio or perms.PDSapp.delete_dominio %}
						<td style="width:20px;">
							{% if perms.PDSapp.change_aspectolegal %}
							<a href="{% url 'PDSapp:editar_aspecto_legal' aspectolegal.id %}">Editar <i class="fas fa-edit color_update"></i></a>
							{% endif %}
							{% if perms.PDSapp.change_aspectolegal and perms.PDSapp.delete_aspectolegal %}
							 |
							{% endif %}
							{% if perms.PDSapp.delete_aspectolegal %}
							<a href="{% url 'PDSapp:eliminar_aspecto_legal' aspectolegal.id %}">Eliminar <i class="fas fa-trash-alt color_delete"></i></a>
							{% endif %}
						</td>
						{% endif %}
					</tr>
				{% endfor %}
				</tbody>
			</table>
		</div>
	</div>

{% endblock %}

PDSapp/templates/PDSapp/lista_recomendacion.html
{% extends "PDSapp/base.html" %}
{% load bootstrap4 %}

{% block title %}Recomendaciones{% endblock %}

{% block active_navbar_lista_recomendacion %}<a class="nav-link active" href="{% url 'PDSapp:lista_recomendacion' %}">Recomendaciones</a>{% endblock %}


{% block content_head %}
<div class="row mt-2">
	<div class="col-sm-6 col-md-6 col-lg-9"><h2>Recomendaciones</h2></div>
	<div class="col-sm-6 col-md-6 col-lg-3">
		{% if perms.PDSapp.add_recomendacion %}
		<a href="{% url 'PDSapp:crear_recomendacion' %}" class="btn btn-success btn-block">Crear Recomendación</a>
		{% endif %}
	</div>
</div>
{% endblock %}


{% block content_body %}
	<div class="row">
		<div class="col-md">
			<table class="table table-striped table-hover">
				<thead>
					<tr>
						<th>Dominio/s</th>
						<th>Control</th>
						<th>Recomendación</th>
						<th>Fuente</th>
						<th>Fecha de creación</th>
						<th>Fecha de actualización</th>
						<th>Fecha de aplicación</th>
						<th>Responsable/s</th>
						<th>Cargo responsable/s</th>
						<th>Aprobado por</th>
						<th>Estado</th>
						{% if perms.PDSapp.change_recomendacion or perms.PDSapp.delete_recomendacion %}
						<th>Accion</th>
						{% endif %}
					</tr>
				</thead>

				<tbody>
				{% for recomendacion in recomendaciones %}
					<tr>
 						<td style="width:80px;">{{recomendacion.control.dominio.nombre}}</td>
 						<td style="width:80px;">{{recomendacion.control.nombre}}</td>
 						<td style="width:100px;">{{recomendacion.descripcion}}</td>
 						<td style="width:80px;">{{recomendacion.fuente}}</td>
 						<td style="width:80px;">{{recomendacion.fecha_creacion}}</td>
 						<td style="width:80px;">{{recomendacion.fecha_actualizacion}}</td>
 						<td style="width:80px;">{{recomendacion.fecha_aplicacion}}</td>
 						<td style="width:80px;">
 							{% with recomendacion.control.dominio.perfil.all as perfiles %}
				              {% if perfiles %}
				                {% for perfil in perfiles %}
				                <span class="badge badge-light">{{perfil.user.username}}</span>
				                {% endfor %}
				              {% endif %}
				            {% endwith %}
				        </td>
 						<td style="width:80px;">
 							{% with recomendacion.control.dominio.perfil.all as perfiles %}
				              {% if perfiles %}
				                {% for perfil in perfiles %}
				                <span class="badge badge-light">{{perfil.cargo}}</span>
				                {% endfor %}
				              {% endif %}
				            {% endwith %}
				        </td>
 						<td style="width:80px;">{{recomendacion.aprobado}}</td>
 						<td style="width:80px;">{{recomendacion.estado}}</td>
 						{% if perms.PDSapp.change_recomendacion or perms.PDSapp.delete_recomendacion %}
						<td style="width:10px;">
							{% if perms.PDSapp.change_recomendacion %}
							<a href="{% url 'PDSapp:editar_recomendacion' recomendacion.id %}">Editar <i class="fas fa-edit color_update"></i></a>
							{% endif %}
							{% if perms.PDSapp.change_recomendacion and perms.PDSapp.delete_recomendacion %}
							 |
							{% endif %}
							{% if perms.PDSapp.delete_recomendacion %}
							<a href="{% url 'PDSapp:eliminar_recomendacion' recomendacion.id %}">Eliminar <i class="fas fa-trash-alt color_delete"></i></a>
							{% endif %}
						</td>
						{% endif %}
					</tr>
				{% endfor %}
				</tbody>
			</table>
		</div>
	</div>

{% endblock %}