auth_PDSapp/urls.py
from django.urls import path

from . import views

app_name = 'auth_PDSapp'

urlpatterns = [
    path('login/', views.loginView, name = 'login'),
    path('logout/', views.logoutView, name = 'logout'),
    path('register/', views.registerView, name = 'register'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('PDSapp/', include('PDSapp.urls')),
    path('auth/', include('auth_PDSapp.urls')),
]

auth_PDSapp/models.py
from django.db import models

# Create your models here.

auth_PDSapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from PDSapp.models import Perfil


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
        ]

class PerfilForm(forms.ModelForm):
    class Meta:
        model = Perfil
        fields = ['apellido_materno',
        	'sucursal',
        	'cargo'
        ]

auth_PDSapp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .forms import CreateUserForm, PerfilForm
from django.contrib.auth.decorators import permission_required

from django.contrib.auth.models import User

from django.contrib import messages


def loginView(request):

    template_name = 'auth_PDSapp/login.html'
    data = {}

    logout(request)
    username = password = ''
    if request.POST:
        user = authenticate(
                username=request.POST['username'],
                password=request.POST['password']
            )

        print(username)
        if user is not None:
            if user.is_active:
                login(request, user)

                return redirect('PDSapp:home')
            else:
                print("usuario o pass incorrecta")
                messages.warning(
                    request,
                    'Usuario o contraseña incorrecto!'
                )

        else:
            print("no encuentra user")
            messages.error(
                request,
                'Usuario o contraseña incorrecto'
            )
    return render(request, template_name, data)


def logoutView(request):
    logout(request)
    return redirect('auth_PDSapp:login')

@permission_required('PDSapp.add_perfil')
def registerView(request):
    template_name = 'auth_PDSapp/register.html'
    data = {}

    if request.method == 'POST':
        user_form = CreateUserForm(request.POST)
        perfil_form = PerfilForm(request.POST)
        if user_form.is_valid() and perfil_form.is_valid():
            uf = user_form.save(commit=False)
            pf = perfil_form.save(commit=False)

            pf.user = uf
            uf.save()
            pf.save()
            return redirect('PDSapp:home')

        elif User.objects.filter(username=request.POST['username']).exists():
            messages.warning(
                request,
                'Este nombre usuario ya está en uso'
            )
        else:
            messages.warning(
                request,
                'Registro no válido'
            )
    else:
        user_form = CreateUserForm()
        perfil_form = PerfilForm()

    data = {
        'user_form': user_form,
        'perfil_form': perfil_form

    }

    return render(request, template_name, data)

auth_PDSapp/templates/auth_PDSapp/login.html
{% load static %}
<!doctype html>
<html lang="es-cl">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.0.1">
    <title>PDS App - Login</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/floating-labels/">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="{% static 'css/login.css' %}" rel="stylesheet">
  </head>
  <body>
  	<form class="form-signin" method="POST">{% csrf_token %}
	  <div class="text-center mb-4">
	    <img class="mb-4" src="/docs/4.5/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
	    <h1 class="h3 mb-3 font-weight-normal">PDS App</h1>
	  </div>

	  <div class="form-label-group">
	    <input type="text" id="username" name="username" class="form-control" placeholder="Username" required autofocus>
	    <label for="username">Usuario</label>
	  </div>

	  <div class="form-label-group">
	    <input type="password" id="password" name="password" class="form-control" placeholder="Password" required>
	    <label for="password">Constraseña</label>
	  </div>

	  <div class="checkbox mb-3">
	    <label>
	      <input type="checkbox" value="remember-me"> Recuérdame
	    </label>
	  </div>
	  <button class="btn btn-lg btn-primary btn-block" type="submit">Entrar</button>
	</form>
  </body>
</html>

auth_PDSapp/templates/auth_PDSapp/register.html
{% extends "PDSapp/base.html" %}

{% load bootstrap4 %}

{% block title %}Registrar usuario{% endblock %}

{% block active_navbar_register %}<a class="nav-link active" href="{% url 'auth_PDSapp:register' %}">Registrar usuario</a>{% endblock %}

{% block content_body %}

<div class="container text-center">

  <div class="row justify-content-center">
    <div class="col-md-7 col-lg-5 align-self-center text-center">
      {% bootstrap_messages %}
      <h2 class="h3 mb-3 font-weight-normal">Registrar usuario</h2>

      <form class="px-4 py-3" method="POST" enctype="multipart/form-data">
        {% csrf_token %}


        <div class="form-group">
          <label for="username">Nombre de usuario</label>
          <input type="text" class="form-control" id="username" name="username" placeholder="Usuario">
        </div>
        <div class="form-group">
          <label for="first_name">Nombre</label>
          <input type="text" class="form-control" id="first_name" name="first_name" placeholder="Nombre">
        </div>
        <div class="form-group">
          <label for="last_name">Apellido Paterno</label>
          <input type="text" class="form-control" id="last_name" name="last_name" placeholder="Apellido Paterno">
        </div>
        <div class="form-group">
          <label for="apellido_materno">Apellido Materno</label>
          <input type="text" class="form-control" id="apellido_materno" name="apellido_materno" placeholder="Apellido Materno">
        </div>
        <div class="form-group">
          <label for="email">Email</label>
          <input type="email" class="form-control" id="email" name="email" placeholder="Correo electrónico">
        </div>

        {% bootstrap_field perfil_form.sucursal %}

        <div class="form-group">
          <label for="cargo">Cargo</label>
          <select id="cargo" class="form-control" name="cargo">
            <option>OPERATIVO</option>
            <option>DIRECTIVO</option>
            <option>AMBOS</option>
          </select>
        </div>
        <div class="form-group">
          <label for="password1">Contraseña</label>
          <input type="password" class="form-control" id="password1" name="password1" placeholder="Contraseña">
        </div>
        <div class="form-group">
          <label for="password2">Repita su contraseña</label>
          <input type="password" class="form-control" id="password2" name="password2" placeholder="Contraseña">
        </div>


        <button type="submit" class="btn btn-primary">Registrar</button>
      </form>

    </div>

  </div>

</div>


{% endblock %}